### ISSUE TITLE
Add the text "Default Schemes" in the settings.

### ISSUE THREAD

**Issue by olegvalko-dev** [land0r/mermaid-blocks#3]
Please add the text "Default Schemes" in the block settings so it’s clear that users can click there to see how it works.
<img width="303" alt="image" src="https://github.com/user-attachments/assets/9f3d336c-b646-459b-a120-f410a6ff6ad0" />

**Comment by land0r** [comment]
@oleg-valko-pro version 1.1.0 has the instructions text
<img width="278" alt="image" src="https://github.com/user-attachments/assets/17be0408-3c9d-4d23-bbb7-61c8e7616e66" />
